### ISSUE TITLE
Update cost distance to work with CDH5 and YARN

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#10]
The current version of MrGeo includes a cost distance operation based on the Giraph graph processing API. Issues with that approach are:
* Problems that arose when porting cost distance for use in CDH5 and YARN
* Giraph required that the entire graph be loaded in memory across the cluster at once, thus making cluster requirements for large-scale cost distance computation prohibitive

To resolve these issues, look into re-implementing the algorithm based on a distributed computing architecture like Apache Spark. The GraphX API included in Apache Spark does not require the entire graph to be memory-based, thus improving scalability, and Spark jobs can run under YARN and coexist nicely with other jobs.

An additional benefit of this effort is having a reusable approach for submitting Spark jobs from MrGeo so that we can take advantage of the simplifying distributed programming paradigm offered by Spark beyond just map/reduce.

**Comment by drew-bower** [comment]
How is this coming along?

**Comment by djohnson729** [comment]
I have the code integrated, and small cost distances seem to be working. However, I've run into some difficulty with worldwide. The first time I got out of memory errors. After boosting the cluster and increasing the memory available to each executor, I started getting out of disk space errors. So I'm looking into that now.

**Comment by drew-bower** [comment]
Can you provide a short update before you leave for the day?
