### ISSUE TITLE
GDALUtils is producing bad images from MrsImages

### ISSUE THREAD

**Issue by ttislerdg** [ngageoint/mrgeo#104]

**Comment by panrufio** [comment]
As tested in a different environment, the Dataset.WriteRaster() and Dataset.WriteRaster_Direct() do not always perform correctly on all platforms.  Testing has shown that writing to the bands directly is more reliable.  The GDALUtils.copyToDataset() needs to be able to pull out the multiple bands of a raster and put them directly into the bands of the Dataset.  For examlple:
Band b = dataset.GetRasterBand(num);
b.Fill(-9999);
b.SetNoDataValue(-9999);
b.WriteRaster_Direct(0, 0, width, height, typeOfData, bytesArray);

**Comment by ttislerdg** [comment]
This seems to be fixed...
