### ISSUE TITLE
CostDistance param for value comparison threshold

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#105]
Add a new parameter to the CostDistance map algebra function that is an optional percentage value. When specified, the cost distance algorithm will check to see if a newly computed cost for a pixel is more than "threshold" percent smaller than the current value in order to modify that pixel's cost.

Providing a threshold may speed up processing of the cost distance by preventing the re-processing of pixels if their values change less than the specified threshold. The result may be a cost distance with higher costs, but it in that case it may also finish sooner.

We should not work on this until https://github.com/ngageoint/mrgeo/wiki/Sparkifying-MapAlgebra is completed since it will allow a single "map op" class to register more than once function name and also enables the parameter parsing to be handled differently based on the function name. In this case that allows once class to deal with "CostDistance" and "CostDistanceWithThreshold" for example.

**Comment by ttislerdg** [comment]
This option is OBE
