### ISSUE TITLE
Cost Distance max value of -1

### ISSUE THREAD

**Issue by wncampbell** [ngageoint/mrgeo#110]
Setting a max value of -1 for Cost Distance no longer works, instead resulting in an output raster that QGIS reports as -inf. This should run the cost distance computation to the bounds of the cost surface raster.

Example:
`mrgeo mapalgebra -mm 16 -e "srcPoint = InlineCsv(\"GEOMETRY\", \"'POINT(-110.8090892 33.74918939)'\"); friction = [s3://mrgeo/images/tobler-tiny]; result = CostDistance(srcPoint, friction, -1)" -o s3://mrgeo/images/cd-tiny2`

**Comment by djohnson729** [comment]
I'm not able to reproduce this now.
