### ISSUE TITLE
Cost Distance fails when max cost exceeds bounds of cost layer

### ISSUE THREAD

**Issue by wncampbell** [ngageoint/mrgeo#111]
If the max cost exceeds the bounds of a cost surface layer, the cost distance job will fail. Although the typical MrGeo use case would be on a global layer we should handle this scenario.

**Comment by djohnson729** [comment]
This bug must've been fixed along the way because I can't reproduce it anymore. My guess is that it was fixed with the changes I made to limit the bounds of the friction surface based on the maxCost provided.
