### ISSUE TITLE
Look into eliminating GraphX from cost distance algorithm

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#128]
The GraphX based cost distance algorithm was an upgrade over the old Giraph-based version, however it still suffers from the need for a lot of cluster resources to process very large friction surfaces. Put some thought into a solution that does not require graph processing at all.

**Comment by djohnson729** [comment]
I have been working on this for a few days and have a solution that works for our integration tests. However, I still need to test it at scale. And we still need to determine its performance relative to the current GraphX based algorithm. To do that, I will run it for the same cost distances that @wncampbell used for generating an opportunity volume in #109

**Comment by drew-bower** [comment]
So what are the performance improvements looking like?

**Comment by djohnson729** [comment]
I used a zoom level 9 cost distance with max cost of 2,000,000 that @wncampbell ran for opportunity volume for ticket #109 as a benchmark.

On a 75 node m3xlarge cluster with the GraphX code, it was taking about 49 minutes. With these changes in place, it took 25:34 on the same cluster.

**Comment by drew-bower** [comment]
Nice work. Let's document these results in the wiki. Is the solution still tile based or is it more modaic oriented to minimize the message traffic between nodes?

**Comment by djohnson729** [comment]
It is tile-based. It starts with one changed pixel (which is the source point specified in the cost distance map algebra call). It iterates over all the tiles in the image at the specified zoom level. For each tile, it checks whether it has any changed points in any of its eight neighbors. If so, it re-processes that tile based on those changes. If any of the edge pixels between that tile and its eight neighbors change during the processing, it remembers those changes for the next pass. This continues until there are no more changed points.

I wrote another issue for testing a mosaic'ed solution. But that processing would be exactly the same except for effectively larger tiles as well as the pre-step of performing the mosaic and a post-step of pulling our tiles back out of the mosaic.
