### ISSUE TITLE
Add z-scores for a given set of rasters

### ISSUE THREAD

**Issue by drew-bower** [ngageoint/mrgeo#138]
Z-Score
DEFINITION OF 'Z-SCORE'
A Z-Score is a statistical measurement of a score's relationship to the mean in a group of scores. A Z-score of 0 means the score is the same as the mean. A Z-score can also be positive or negative, indicating whether it is above or below the mean and by how many standard deviations.

http://www.investopedia.com/terms/z/zscore.asp#ixzz3qc9T8Clg

**Comment by ttislerdg** [comment]
We need to chat about this.  It's not clear how it would work

**Comment by drew-bower** [comment]
So in the past both Lou and I have implemented the following in an ordered set of rasters:

1) compute average value per pixel
2) compare each ordered raster to the average to compute the z-score of each raster. 

The result is an ordered set of z-score rasters. 

I'll be by to discuss once I get into the office.

**Comment by djohnson729** [comment]
Recent changes to MrGeo should support this need by using the "stats" map algebra function in combination with the MrGeo Python bindings. Here's the overview of what the python script would look like:

<pre>
# Initialize MrGeo context
mrgeo = MrGeo()

# Construct the list of images to be z-scored
images = []
images.append(mrgeo.load_image("image1"))
images.append(mrgeo.load_image("image2"))

# Compute std dev for each individual pixel across all of the images
stddev = stats(images, "stddev")

# Compute mean for each individual pixel across all of the images
mean = stats(images, "mean")

# Compute the z-score for each pixel
zscores = []
for i in images:
  zscores.append((i - mean) / stddev)
</pre>

Once you have the list of z-score images, you can either run additional map algebra on them or save them (using the save map algebra function).

**Comment by drew-bower** [comment]
Can you tag Chad Shuey on this?
