### ISSUE TITLE
404 on Maven Plugin 

### ISSUE THREAD

**Issue by Prindle19** [ngageoint/mrgeo#17]
There is also a custom Maven plugin the team built to make discovering jars easier. Download it from our git wiki and manually install it to your local repo as follows (making sure you are not in the MrGeo source directory):

There is no file there.

**Comment by ttislerdg** [comment]
Sorry, I was in the middle of redeploying it.  Try again.  

Note it is now a tar.gz file, it includes both the jar and its associated pom.xml file

**Comment by chrisbennight** [comment]
If you want public hosting I can set you up with some S3 access for MrGeo open source usage - here's an example of a maven repo on S3.   
https://github.com/wbinglee/maven-s3-repo

**Comment by ttislerdg** [comment]
File is OK
