### ISSUE TITLE
Fix output raster type for raw binary math map algebra functions

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#189]
When a raw binary math operation is performed, there are some cases where the output raster type will be wrong.

 * When both args are rasters, it uses the type of the first one. But it should use the "largest" type between the two so that adding an int raster to a float raster should produce a float raster.
 * When one arg is a constant, the output raster type will be the same as the raster arg type. However, if the raster is type int, and the arg is float, the output type should be float.

**Comment by ttislerdg** [comment]
It looks like a similar problem could occur in RawUnaryMapOp as well
