### ISSUE TITLE
skip-all-tests profile doesn't work

### ISSUE THREAD

**Issue by pliguori** [ngageoint/mrgeo#19]
It would look like creating a profile called "skip-all-tests" should help in skipping the tests at mvn build time.
Unfortunately it doesn't or at least I didn't find the right way to do it.
How I made it skipping the tests was actually setting 2 variables called mrgeo.core.test.skiptests and mrgeo.core.integration.skiptests to true.

**Comment by ttislerdg** [comment]
Some of our local build environment was left out of the POMs when we opensourced.  The skipping should now work as you think.

the skip.all.test profile should enable skipping all the tests.

**Comment by chrisbennight** [comment]
General convention is just to use -DskipTests -DskipITs 
(depending on what you want to skip)
(not a huge deal, but I think that's what people would expect by default)

**Comment by mfsny** [comment]
Had the same issue and could get around it using:
```
scripts/mvn-build <module> cdh530 --yarn \
-Dmaven.scala.checkConsistency=false \
-Dskip.mrgeo.core.tests=true -Dskip.mrgeo.core.integration.tests=true \
-Dskip.mrgeo.vector.tests=true -Dskip.mrgeo.vector.integration.tests=true \
-Dskip.mrgeo.mapalgebra.tests=true -Dskip.mrgeo.mapalgebra.integration.tests=true \
-Dskip.mrgeo.dataprovider.tests=true -Dskip.mrgeo.dataprovider.integration.tests=true \
-Dskip.mrgeo.cmd.tests=true -Dskip.mrgeo.cmd.integration.tests=true \
-Dskip.mrgeo.pig.tests=true -Dskip.mrgeo.pig.integration.tests=true \
-Dskip.mrgeo.services.tests=true -Dskip.mrgeo.services.integration.tests=true
```
but glad to hear it is fixed now.

**Comment by ttislerdg** [comment]
Closing as fixed
