### ISSUE TITLE
Write a new convert map algebra function for converting data types

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#200]
Useful for converting from an int raster to a float raster for example. This is useful for a case like executing a "pow" operation on two int inputs. In this case, by default, the output raster type would also be int, and depending on the input pixel values, it could overflow the int type. To handle this, you could use the convert operator to force one of them to a float beforehand which would change the output type to float.

We also need to consider how to handle overflows when converting to smaller data types (e.g. int to byte). Options include truncation. modulo, and re-sampling the inputs to a min/max value range.

**Comment by drew-bower** [comment]
@what would happen with a "con" statement on a float imager where you are reclassifying a raster into categories (nominal data scaling)?

**Comment by djohnson729** [comment]
Looking at the code, it looks like it will use float in that case. This would be a good case for the user to run convert on that output to downgrade the type for saving space.

**Comment by drew-bower** [comment]
Something like this would be useful:

int(nameOfBigRaster, 4) where 4 is the number of bits (giving me access to 0-15 in my recode). This is good for nominally scaled data. In the case of ordinal and or interval scaled data, I could see the use case of fitting a float raster into an 8 bit integer where the min and max input raster values are fit to 0 and 255 respectively.
