### ISSUE TITLE
attach-effective-pom fails with mrgeo-mapalgebra

### ISSUE THREAD

**Issue by willtemperley** [ngageoint/mrgeo#21]
I'm having some issues building the mapalgebra modules.  I'm using Maven 3.0.5 as this is the only version I can get to work with the pomtools-maven-plugin (newer versions complain of a missing class). 

I get the following error after all the child mapalgebra modules build, and I can't figure out why it's happening.  I wonder if someone could give me some pointers here please? Thanks.

Failed to execute goal org.codehaus.mojo:build-helper-maven-plugin:1.9.1:attach-artifact (attach-effective-pom) on project mrgeo: Execution attach-effective-pom of goal org.codehaus.mojo:build-helper-maven-plugin:1.9.1:attach-artifact failed: For artifact {org.mrgeo:mrgeo:0.5.0-cdh5.1.0-SNAPSHOT:pom}: An attached artifact must have a different ID than its corresponding main artifact

**Comment by ttislerdg** [comment]
What version of hadoop are you using?  I can try to reproduce it myself.

**Comment by willtemperley** [comment]
Thanks for looking.  We're on CDH 5.1.3, which uses hadoop 2.3.0.

**Comment by ttislerdg** [comment]
I could not reproduce the failed goal, but I did notice we didn't currently have build profiles for CDH 5.1.3. and have added them to the POMs and build scripts.  Can you give them a try and see if anything changes.

You an use `./build cdh513` (`./build cdh513 --yarn` if using YARN) to build.

**Comment by willtemperley** [comment]
Great to have a 5.1.3 version, cheers! All built, problem solved, something in my settings.xml was causing the issue, not 100% sure what.
