### ISSUE TITLE
Create a map algebra function for converting radians to degrees and percent

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#214]
In cases where the same slope output is needed in radians, degrees and percent as three separate layers, this map algebra function allows the user to calculate the slope once in radians (which is a more expensive neighborhood-based operation), and then use this new converter function to get it in degrees or percent.

**Comment by ttislerdg** [comment]
There is no need to create a function for this.  It is simple math:

rad to deg:   mult by 180/pi (i.e. mult. by 57.2958)
deg to rad:   mult by pi/180 (i.e mult by 0.0174533)

rad to pct: divide by 2pi times 100 (divide by 628.319, or mult by 0.00159154824)

etc.

**Comment by djohnson729** [comment]
True true - my bad
