### ISSUE TITLE
Modify isNoData operation to work with inputs having missing tiles and different nodata values

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#234]
Con does not behave as a user might expect in a case where one or more of the inputs are missing tiles that the other inputs do have. The output ends up with unexpectedly missing tiles. Also, we want to make sure it chooses an appropriate nodata value when multiple inputs have different nodata values (or even different types).

I recently added an image in mrgeo-mapalgebra/mrgeo-mapalgebra-integrationtests/testFiles/kph-for-small-elevation that can be used along with small-elevation for testing because the kph image has some missing tiles that small-elevation has.

**Comment by ttislerdg** [comment]
Actually,  This is _only_ the case when one of the conditional expressions is IsNodata().  In all other cases, it is acting fine.

This may mean the solution would be to have the isNodata mapop actually output data (1s, the true case) where there are missing tiles within the image.
