### ISSUE TITLE
Missing dependency warning

### ISSUE THREAD

**Issue by akarmas** [ngageoint/mrgeo#277]
When executing "mrgeo ingest" command, some warnings regarding missing dependencies show up.
They are of the form:
WARN mrgeo.utils.DependencyLoader: Could not find dependency in classpath: [jar-name].jar
e.g.
WARN mrgeo.utils.DependencyLoader: Could not find dependency in classpath: hadoop-yarn-server-web-proxy-2.2.0.jar

**Comment by djohnson729** [comment]
Can you please run the same build command you've been using and add the "dependency:tree" goal and a -Dverbose=true and paste the output to this ticket (e.g. ./build  -Dverbose=true dependency:tree)?

**Comment by akarmas** [comment]
Please find the output to the build command attached.

[output.txt](https://github.com/ngageoint/mrgeo/files/224114/output.txt)

**Comment by ttislerdg** [comment]
Closing as OBE
