### ISSUE TITLE
Flat pixels, aspect value

### ISSUE THREAD

**Issue by chadshuey** [ngageoint/mrgeo#294]
Pixels that have all neighbors with the same elevation as the pixel are perfectly flat, and thus have no aspect.  Currently, these pixels end up as aspect 90 (due east) due to the slope and aspect algorithms we use.  This is problematic in that flat areas will have lots of false east facing pixels.  Other possible values should be considered and made available such as Null, No Data, 0, -1.

**Comment by djohnson729** [comment]
This was done in #352
