### ISSUE TITLE
MrGEO does not build when using latest version of Maven (3.3.1)

### ISSUE THREAD

**Issue by techchrj** [ngageoint/mrgeo#33]
Could not get the source tree to build using Maven 3.3.1 without failing.  Had to roll my maven version back to 3.0.5 to get it to build the jars properly.

**Comment by ttislerdg** [comment]
Ends up there was a breaking API change in maven between 3.0.x and 3.1.x.  The project transitioned from using sonotype aether libraries to eclipse aether libraries.  These two are not compatible.

I made a new version of the pomtools-maven-plugin to take that into account.  It has been [loaded](https://github.com/ngageoint/mrgeo/wiki/pomtools-maven-plugin/pomtools-maven-plugin-0.1.2.tar.gz) and linked in [our dependency instructions](https://github.com/ngageoint/mrgeo/wiki/MrGeo-Build-Dependencies)

The old 0.1.1 version is still needed for maven 3.0.x compatibility, which is the maven version included in the default ubuntu distributions.

Committed with d9774709f1dc7ce3252e559ec7fa6c0173c889b9
