### ISSUE TITLE
rasterizevector map algebra function should accept bounds

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#349]
This will filter the set of features to rasterize to only those that intersect the bounds. The bounds should be specified either by minX, minY, maxX, maxY or another raster from which the bounds are obtained (similar to other map ops like crop).

**Comment by djohnson729** [comment]
To clarify, the Scala map op for RasterizeVector and RasterizePoints already support bounds. We need to change the python interface to them to allow bounds (and rasterForBounds) to be passed - i.e. the "create" methods in the map ops.

**Comment by ericwood73** [comment]
I'll take this one since it is similar to #347

**Comment by ericwood73** [comment]
I have discovered that there are RasterizeVectorExact and RasterizePointExact map operations that accept a bounds available in python.  I believe they satisfy this issue.
