### ISSUE TITLE
Mrgeo info doesn't find MrsPyramid

### ISSUE THREAD

**Issue by maptopixel** [ngageoint/mrgeo#357]
The mrgeo info command is currently broken.

Eg. if I run:

> ./bin/mrgeo info greece

where greece is a MrsPyramid dataset, I get: 

> MrsPyramid does not exist: "greece"

I think it's useful command so would be nice to keep if possible.

**Comment by ttislerdg** [comment]
It looks like the command isn't using the DataProvider interface to get the pyramid.  I'll change it...
