### ISSUE TITLE
Change the EMR builds to contain a unique final.classifier 

### ISSUE THREAD

**Issue by ttislerdg** [ngageoint/mrgeo#376]
Right now, each emr build is basically building apache 2.7.2 builds, but each one has the same `final.classifier` within the profile.  So each emr build is overwriting the last one.  Change the pom so the each emr profile has a unique `final.classifier`

At the same time, remove the `.` and `-` from the profile names to be consistent with the other profiles

**Comment by djohnson729** [comment]
Closed by 8eb45a851e07caa40575360b2acb6e1890f7cd98
