### ISSUE TITLE
Re-factor ingest to use Spark

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#39]
Update the ingest code to make use of Spark for better performance.

**Comment by djohnson729** [comment]
This will involve some groundwork to get Spark running within MrGeo. Most information on the internet shows how to submit Spark jobs from the command line, but it seems that there is not much out there related to running Spark jobs programmatically (which we need for MrGeo). Additionally, there is some work that has to be done just to figure how to run Spark in our environment.

**Comment by ttislerdg** [comment]
Closed with commit 67150ae833219002f5cf508501cdbacb12492f25
