### ISSUE TITLE
Allow mrgeo-emr.py to support additional yarn-site, mapred-site and spark-defaults changes

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#396]
The mrgeo-emr.py script has a section for configuration settings for the cluster for yarn-site, mapred-site and spark-defaults settings supported by EMR. Occasionally, users might need to include additional settings in them, and rather than forcing them to modify the mrgeo-em.py script (which they would have to do today), allow the JSON config passed to mrgeo-emr.py to include these settings.

**Comment by ttislerdg** [comment]
Closed in 49e14276a0c14ce6e8f13d9fc2997a7f46337fa9
