### ISSUE TITLE
Unable to load GDAL shared libraries

### ISSUE THREAD

**Issue by anirusharma** [ngageoint/mrgeo#400]
I have noticed that gdal.path includes /usr/lib/jni

I have coped GDAL .so and jar file in this path and then I run 
mrgeo-cmd/src/main/scripts/mrgeo ingest  -o dem1181 mrgeo/raw-images/dem1181.tif

I still get this error . Request your guidance how to resolve it
java.lang.UnsatisfiedLinkError: no osrjni in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.gdal.osr.osrJNI.UseExceptions()V
        at org.gdal.osr.osrJNI.UseExceptions(Native Method)

**Comment by djohnson729** [comment]
Do you have libgdal-java installed as well? Also, there is a setting in the mrgeo.conf file named gdal.path. Make sure that includes the paths where your GDAL and GDAL java libraries are.

**Comment by ttislerdg** [comment]
Did you ever get this resolved?

**Comment by ttislerdg** [comment]
Assuming the problem was resolved...
