### ISSUE TITLE
Cost distance incorrectly processes friction surface if nodata is not NaN

### ISSUE THREAD

**Issue by jamesmcclain** [ngageoint/mrgeo#440]
I have been doing some experimenting with the `CostDistance` function, and I have found what appears to be some incorrect behavior.

My input at the command line looks something like this
```bash
mrgeo ingest -o friction file:///tmp/friction.tif # ingest friction layer
mrgeo mapalgebra -s /tmp/costdistance -b -o cost  # run map algebra script
mrgeo export -s -o /tmp/cost cost                 # produce a file called /tmp/cost.tif
```
and my `costdistance` script looks like this
```
srcPoint = [/mrgeo/vectors/points.shp];
result = CostDistance(srcPoint, [friction], 400000);
```

Given those, I get output that looks something like this
![screenshot from 2017-02-07 12 41 02](https://cloud.githubusercontent.com/assets/11281373/22703829/8d68c748-ed33-11e6-8ac2-bab3f766d385.png)
(where the dots are the starting sites).

In particular, I am looking at the dark bands on top and sides of the image, and the growth that is occuring from those dark bands.  I have not done any in-depth debugging, but it appears to me that there may be low or zero values around the periphery of the ingested friction layer that allow the propagation to continue around the edges of the image longer than it should.

Thank you.

**Comment by djohnson729** [comment]
I suspect that you're right about the low friction values around the edges. How was the source friction surface created? Did you look at the pixel values of the friction surface around the edges?

**Comment by jamesmcclain** [comment]
I am fairly certain that the edge values are non-zero.  The friction layer is a rasterized road network and it appears that road areas have value 1 and non-road areas have value 5.

The possibility of user error in the ingest of the layer is not out of the question, though.

**Comment by jamesmcclain** [comment]
For completeness, I should add that the observation was made using [this container](https://github.com/jamesmcclain/MrGeoDocker) which is based on mrgeo sha 0c6ed4a7e66bb0923ec5c570b102862aee9e885e .

**Comment by jamesmcclain** [comment]
This sequence (with `-c` during the ingest, but w/o `-nd 5`):
```bash
mrgeo ingest -c -o friction file:///tmp/road_friction.tif
mrgeo mapalgebra -s /tmp/costdistance -b -o cost
mrgeo export -s -o /tmp/cost cost
```
produced this file:
![screenshot from 2017-02-22 14 18 07](https://cloud.githubusercontent.com/assets/11281373/23228350/3ad2e9ae-f90a-11e6-8d5c-80e25be4b3ab.png)

**Comment by djohnson729** [comment]
Looking at the cost distance code, I found the problem. The code is written to assume that the friction surface uses NaN for its nodata value. I'm going to change the description of this ticket to reflect that. In the meantime, you can work around the problem by using "convert([friction], "float32")" as teh friction surface argument to the costdistance function. Thanks for reporting. The cost distance result after the conversion looks like:

![image](https://cloud.githubusercontent.com/assets/7021622/23258061/8b2a8724-f994-11e6-805a-4ad59d4e9912.png)

**Comment by jamesmcclain** [comment]
Thanks much.
