### ISSUE TITLE
Artifacts in output of slope operations

### ISSUE THREAD

**Issue by wncampbell** [ngageoint/mrgeo#47]
I'm seeing linear artifacts in the slope output computed from the global aster layer. 

To reproduce:

1. Compute slope on s3://mrgeo/images/aster-30m in radians
`mrgeo mapalgebra -e "result = slope([s3://mrgeo/images/aster-30m],\"rad\")" -o s3://mrgeo/images/slope-rad`
2. Build Pyramids
3. Visualize with any color scale

Screenshots to follow

**Comment by wncampbell** [comment]
Visible with any color scale.

![slopeartifacts1](https://cloud.githubusercontent.com/assets/3909938/8368294/64dc406a-1b76-11e5-9700-0b3bb1bb253f.png)

![slopeartifacts2](https://cloud.githubusercontent.com/assets/3909938/8368290/52700830-1b76-11e5-9b32-ddb14688579a.png)

**Comment by drew-bower** [comment]
@wncampbell this looks like raw srtm. What's the source?

**Comment by wncampbell** [comment]
@drew-bower Source is Aster GDEM v2. I'm ingesting SRTM from s3 now for a comparison. These screenshots are the output of the slope operation.
