### ISSUE TITLE
Tile boundary artifacts after ingest of SRTM data

### ISSUE THREAD

**Issue by wncampbell** [ngageoint/mrgeo#53]
Seeing missing data for every tile boundary in the ingest, screenshots below. To reproduce:

`mrgeo ingest -o s3://mrgeo/images/srtm-elevation -sk -sp -z 10 -v s3://mrgeo-source/srtm-90`
`mrgeo buildpyramid s3://mrgeo/images/srtm-elevation`

500 m3.xlarge 
Ingest - 9:30.51elapsed
BuildPyramid - 11:16.55elapsed

![srtm2](https://cloud.githubusercontent.com/assets/3909938/8381303/dd26b046-1bf8-11e5-8909-6419d1d56e8b.JPG)

![srtm1](https://cloud.githubusercontent.com/assets/3909938/8381299/d91fb38a-1bf8-11e5-8890-3ef4c0c80d73.JPG)

![srtm3](https://cloud.githubusercontent.com/assets/3909938/8381304/e0379c46-1bf8-11e5-87bf-1d4d7a09757f.JPG)

**Comment by wncampbell** [comment]
Adding the nodata flag for the correct srtm nodata value did not make a difference, output is the same.

**Comment by ttislerdg** [comment]
Can you tell if the artifact is nodata, or another value?

**Comment by wncampbell** [comment]
The artifacts are nodata. If I do not specify a nodata value on ingest, the pixel value for the artifacts is -32768 (nodata value of the source data). When I ingest using the nodata flag set to this value, the artifacts are nodata. I verified by exporting geotiffs at their native resolution.

**Comment by wncampbell** [comment]
Verified working, looks great.

![validsrtm](https://cloud.githubusercontent.com/assets/3909938/8455592/e2f2ac80-1fd3-11e5-8bc8-b66e12105b52.png)


Btw, using latest release the ingest took 5min and pyramids took 5min on 100 nodes.

**Comment by drew-bower** [comment]
Can you re-run the ingest on 20 nodes?  I'd like to mentally compare what we did back when on the 20 node. 

This is pretty fast, into S3 to boot.
