### ISSUE TITLE
Generate base data layers - SRTM

### ISSUE THREAD

**Issue by wncampbell** [ngageoint/mrgeo#58]
Generate the following layers globally for SRTM

- Slope (rad)
- Aspect (rad)
- Hillshade
- Tobler
- Water bodies

**Comment by drew-bower** [comment]
Can we run these across a 7 node, 20 node, 100 node, 500 node?

Also when you run tobler will that be the full script or in piece parts?

Last would it also be possible to run this on a 7 node bare metal cluster without S3?

Hum maybe this is getting too close to the benchmarking task, but I can't help but ask the questions..  Nice work guys.

**Comment by wncampbell** [comment]
Sure thing. I can run tobler either way, was planning on full script.
