### ISSUE TITLE
WMS becomes unresponsive after a few requests

### ISSUE THREAD

**Issue by wncampbell** [ngageoint/mrgeo#83]
Tested with QGIS. After panning around a bit and making roughly 10 GetMap requests the WMS service becomes unresponsive. QGIS shows that the request timed out, no errors on the server. Unable to query GetCapabilities until a restart of mrgeo webserver. 

Webserver seems to start correctly:

com.sun.jersey.server.impl.application.DeferredResourceConfig$ApplicationHolder <init>
INFO: Instantiated the Application class org.mrgeo.application.Application
Found MrGeo resource: org.mrgeo.resources.version.VersionResource
Found MrGeo resource: org.mrgeo.resources.wms.WmsGenerator
Found MrGeo resource: org.mrgeo.resources.job.JobResource
Found MrGeo resource: org.mrgeo.resources.mrspyramid.MetadataResource
Found MrGeo resource: org.mrgeo.resources.mrspyramid.ColorScaleResource
Found MrGeo resource: org.mrgeo.resources.about.AboutResource
Found MrGeo resource: org.mrgeo.resources.tms.TileMapServiceResource
Found MrGeo resource: org.mrgeo.resources.KmlGenerator
Found MrGeo resource: org.mrgeo.resources.mrspyramid.RasterResource
Found MrGeo resource: org.mrgeo.resources.wcs.WcsGenerator
Found MrGeo resource: org.mrgeo.resources.version.VersionResource
Found MrGeo resource: org.mrgeo.resources.wms.WmsGenerator
Found MrGeo resource: org.mrgeo.resources.job.JobResource
Found MrGeo resource: org.mrgeo.resources.mrspyramid.MetadataResource
Found MrGeo resource: org.mrgeo.resources.mrspyramid.ColorScaleResource
Found MrGeo resource: org.mrgeo.resources.about.AboutResource
Found MrGeo resource: org.mrgeo.resources.tms.TileMapServiceResource
Found MrGeo resource: org.mrgeo.resources.KmlGenerator
Found MrGeo resource: org.mrgeo.resources.mrspyramid.RasterResource
Found MrGeo resource: org.mrgeo.resources.wcs.WcsGenerator
Found MrGeo provider: org.mrgeo.resources.serviceproviders.MrsPyramidServiceProvider
Found MrGeo provider: org.mrgeo.resources.serviceproviders.VersionServiceProvider
Found MrGeo provider: org.mrgeo.resources.serviceproviders.TmsServiceContextProvider
Found MrGeo provider: org.mrgeo.resources.serviceproviders.MrsPyramidServiceProvider
Found MrGeo provider: org.mrgeo.resources.serviceproviders.VersionServiceProvider
Found MrGeo provider: org.mrgeo.resources.serviceproviders.TmsServiceContextProvider

Cluster specs - 100 node m3.xlarge

**Comment by ttislerdg** [comment]
This is because of the limits in the number of connections between S3 and EMR.  We’ve seen this during buildpyramid, and mapalgebra commands as well.  The short-term solution is to remove the mrgeo’s cached readers.  The downside is without the cache, these unresponsive errors will happen a lot.

We’re working on a permanent solution now.
