### ISSUE TITLE
WMS/WCS fails if entire request is in an area of no data

### ISSUE THREAD

**Issue by ttislerdg** [ngageoint/mrgeo#86]
If we request an area with the start and end tile in an area with no data, the KVIterator (?) that is returned from the image.getTiles() will keep cycle through all the remaining partitions one-by-one until the end is reached.  This is a _very_ slow process and will usually result in a timeout.

This request from QGIS to the aster-30m-slope image in S3 reproduces the error.

http://<addr>/mrgeo/wcs?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&FORMAT=geotiff&COVERAGE=aster-30m-slope&BBOX=-0.00051498388529592,-0.0002574917993533,0.00051498388529592,0.0002574917993533&CRS=EPSG:4326&RESPONSE_CRS=EPSG:4326&WIDTH=6&HEIGHT=3

**Comment by drew-bower** [comment]
Is this one still pending?

**Comment by ttislerdg** [comment]
Completed, just needs to be tested.

**Comment by wncampbell** [comment]
I'll test. Has the build of mrgeo on s3 been updated?

**Comment by ttislerdg** [comment]
Working...
