### ISSUE TITLE
WMS/WCS GetCapabilities cache

### ISSUE THREAD

**Issue by ttislerdg** [ngageoint/mrgeo#96]
The GetCapabilities calls in WCS and WMS can take a very long time.  It would be nice to create some sort of autoupdating cache that would periodically update to make those request much faster.

The same might be implemented for the DescribeCoverage calls

I noticed when doing a WCS request from QGIS, the 1st thing it does each time it's getting new data it to do a GetCapabilities followed by a DescribeCoverage.  These each take multiple seconds to complete.

**Comment by wncampbell** [comment]
This is probably related but I can no longer use WMS with Qgis. The GetCapabilities request appears to run for a while and then qgis errors with:

Failed to download capabilities:
Download of capabilities failed: Error downloading http://localhost:9444/mrgeo/wms?SERVICE=WMS&REQUEST=GetCapabilities - server replied: Bad Request

**Comment by wncampbell** [comment]
More detail, could this be a bad layer?

`
<ServiceExceptionReport version="1.3.0">
<ServiceException>
<![CDATA[
org.mrgeo.data.DataProviderNotFound: Unable to find a MrsImage data provider for 19:01 at org.mrgeo.data.DataProviderFactory$MrsImageLoader.call(DataProviderFactory.java:393) at org.mrgeo.data.DataProviderFactory$MrsImageLoader.call(DataProviderFactory.java:348) at com.google.common.cache.LocalCa
...
`

**Comment by wncampbell** [comment]
My post is due to colon characters in the s3 object name. Replacing this character fixes the issue I was seeing.

**Comment by ttislerdg** [comment]
This issue is no longer valid.  There is now a geoserver plugin that better manages WMS/WCS
