### ISSUE TITLE
Investigate using larger tile sizes for cost distance performance

### ISSUE THREAD

**Issue by djohnson729** [ngageoint/mrgeo#99]
Look at combining multiple MrGeo tiles into a larger mosaic to reduce the number of vertices required for the graph processing and possibly boost performance.

**Comment by djohnson729** [comment]
After making changes and testing these on a 75-node cluster in EMR, I found that it actually ran slower. This result appears to be due to size of the data being serialized. For the following cost distance, the time for the original code was 13:38 and with these changes, it increased to 14:39.

time bin/mrgeo mapalgebra -mm 8 -e "srcPoint = InlineCsv("GEOMETRY", "'POINT(9.029234 45.223345)'"); friction = [s3://mrgeo/images/tobler-raw-spm]; result = CostDistance(srcPoint, 9, friction, 2000000)" -o s3://mrgeo/images/cdout

**Comment by drew-bower** [comment]
So dos you make 512 tiles to begin with, or have a mosaic operation from 256 included?

**Comment by drew-bower** [comment]
Dos=did

**Comment by djohnson729** [comment]
I wrote code to mosaic from 512 pixel tiles (which is our default) to 1024 tiles.

**Comment by drew-bower** [comment]
When you ran the tests did you try various combinations of cost distance scenarios with varying parameters?  Further I'd be curious to see what the impact would be for native 1024 tiles..

**Comment by drew-bower** [comment]
@djohnson729 So to summarize:
* this experiment starts with 512 tiles, mosaics them into larger tiles (1024), then runs the operation.
* this methodology is slightly slower because of the expense of the mosaic operation to 1024 tiles

What would you expect to see if:
* the cost distance operation ran on native 1024 tiles?
* If the operation were run over an area that was reasonably sized (AKA a size that could be handled on the desktop) intead of mosaicing to 1024, what if the AOI was merged into one mosaic (effectively removing dependencies on messaging beween tiles?)

**Comment by herseyt** [comment]
Drew -

I would be more curious to know if the results for cost distance were more accurate or improved when the IB algorithms are implemented...

Tom

**Comment by drew-bower** [comment]
@herseyt  You're right. Add an issue and let's get it going.

**Comment by drew-bower** [comment]
@herseyt

Further, let's setup a meeting with the right IB stakeholders. I don't remember seeing a copy of their paper. From what I can recall it will perform much better in flat areas.

**Comment by djohnson729** [comment]
@drew-bower With regard to your earlier question - with the testing I did for this ticket, what I saw was that the work to mosaic at the start of cost distance and the work to re-tile it at the end increased the overall processing time.

Using 1024 native tiles, while possibly improving cost distance performance would slow down image serving. @ttislerdg and Ameet put a lot of thought into tile sizes and chose 512 as the best balance for processing and serving.

**Comment by drew-bower** [comment]
@djohnson729 I agree in that point. But I can't think of a useful scenario where users really care to display their friction surfaces. In wondering if it would make sense to create the concept of an analytic mrgeo raster with larger dimensions, then write the result back into a conventional 512 tile.  

Thoughts?

**Comment by djohnson729** [comment]
@drew-bower That goes back to the problem where the mosaicing and re-tiling work in addition to the 1024 cost distance took longer than just running it all with 512.
